version: "3"
services:
  user-service-container:
    image: user_rest_service
    container_name: user_rest_service_container
    ports:
      - "8090:8090"
    networks:
      - user-service-network
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - user-service-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  user-service-network: 